### PR TITLE
upgrade-lb-explorer

### PR DESCRIPTION
**Pull request by jannyHou**
Change loopback-explorer to loopback-component-explorer

### CODE REVIEW

**Comment by jannyHou** [comment]
@crandmck Hi Rand, I did lb-explorer related changes according to your guideline, can you review it? Thanks!

**Comment by crandmck** [comment]
LGTM.  I ran the branch, but I don't have Google or FaceBook client IDs, so I didn't test that part, but I'm assuming it works.

**Comment by crandmck** [comment]
LGTM!

**Comment by 0candy** [comment]
Connect to https://github.com/strongloop/loopback-example-xamarin/issues/1

**Pull request merged**
